version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: " "
      POSTGRES_DB: forms
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres: @db/forms"
    ports:
      - "8000:8000"

volumes:
  postgres_data: